### PR TITLE
🍞

### PR DESCRIPTION
**Pull request by samccone**
<p align="center">

</p>

### CODE REVIEW

**Comment by samccone** [comment]
screen shot 2015-09-10 at 5 29 57 pm

**Comment by justinfagnani** [comment]
Any chance you could split this PR up? It has a lot of unrelated changes, some of which I could trivially merge and some of which require more discussion.

**Comment by samccone** [comment]
hey @justinfagnani all updated for you :)

**Comment by justinfagnani** [comment]
Sweet. Taking a look

**Comment by justinfagnani** [comment]
I have some style tweaks in my head, but I think I'd rather get this in and play with some ideas on top of it.

**Comment by justinfagnani** [comment]
Thanks for the PRs!

**Comment by samccone** [comment]
woot :tada: 

thanks for the awesome tool :hammer: :sparkler: :bridge_at_night:

**Pull request merged**
